name: smart_home
description: Smart Home UI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  fluttericon: ^2.0.0
  ui_common:
    git: https://github.com/brocodev/ui_common.git

flutter:
  uses-material-design: true
  assets:
    - assets/images/

